### PR TITLE
update

### PR DESCRIPTION
**Pull request by snebes**

### CODE REVIEW

**Comment by jschroed91** [comment]
@snebes Looks like this needs a rebase

**Comment by jschroed91** [comment]
@snebes Looks like this is actually the old ListDiff class, maybe? There have been some substantial updates to the ListDiff class a few months ago, I believe

**Comment by snebes** [comment]
@jschroed91 You are correct. I am working on a cdp fork using an old version of the lib and found a "bug".  Or a feature.  Whatever, didn't want to waste my time scoping out what that class is doing since it no longer exists.  And spent more time than I should have trying to PR that change back here for no good reason :)

**Comment by jschroed91** [comment]
@snebes Do you know which tag it's on? We might be able to create an old release branch and you can put up a PR into that, and I can create a new pre-release (0.0.*) tag for the fix.

Otherwise I would suggest upgrading to the latest version, it's much, much better.

**Pull request closed without merging**
