### PR TITLE
HTMLDiff Performance inhancement

### PR DESCRIPTION
**Pull request by SavageTiger**
Hi,

After the warm welcome of my last pull request I got motivated to do some more digging around in the php-htmldiff source to optimize some views in our applications that feel sluggish because of the html differ.

I made some optimizations with pretty amazing results;

- What i did was is replaced some double operators by triple operators, narrow type comparing is way faster in PHP
- Replaced a preg_match that checked for white space with native functions. (seems around 15% faster) depending on the amount of calls
- Rewrote the stripTagAttributes() it created many small arrays, and then converted them back to strings, that is a pretty expensive operation.
- The big one: created a custom version of array_slice that is called many times over in findMatch(), it caches the last request and returns the cached result when the same parameters are passed, this improved the performance dramaticly (in my test case).

There is a performance test (--group performance in phpunit). Here are my results:

(CPU: Intel(R) Core(TM) i7-3630QM CPU @ 2.40GH);

testParagraphPerformance test PHP5.6 : 

v0.1.2 -> 45.75 seconds (memory: 14.50 MB)
master -> 5.93 seconds (memory: 14.50 MB)

testParagraphPerformance test PHP7 :

v0.1.2 -> 7.38 seocnds (memory: 10.0MB)
master -> 1.73 seconds (memory: 10.0MB)

The standard unit tests also feel a little faster, but since those are small its hard to measure.

### CODE REVIEW

**Comment by jschroed91** [comment]
@SavageTiger Just glanced at this this morning, and it all looks very good :+1: I'll go through it more thoroughly a little bit later today - thank you once again for your contributions!

**Comment by jschroed91** [comment]
There are also some major improvements we can do in the diffing algorithms to improve performance. We haven't created issues for them since we haven't had too many contributions up until now, but I'll be sure to create some Github issues with some explanations of improvements that can be made, in case you continue to be motivated ;)

**Comment by SavageTiger** [comment]
Hi @jschroed9, did you find the time to look at my pool request?, If you need some clarification please let me know, happy to help.

**Comment by jschroed91** [comment]
Hi @SavageTiger! Thank you for the ping :) Yes, I did look through it and it all looks great! So happy to have your contributions, feel free to keep them coming!

Merging now.

**Pull request merged**
