### PR TITLE
Fix issues with unicode characters - fixes #71

### LINKED ISSUE #71: Encoding issues with umlauts
I'm not sure if this repo is still maintained but I'd really appreciate some help. I'm having some encoding issues with umlauts and I cannot for the life of me figure out how to fix this. This is the code I'm running:

```php
$oldValue = 'Änderung';
$newValue = 'Test Änderung';

var_dump($oldValue);
var_dump(mb_detect_encoding($oldValue));
var_dump($newValue);
var_dump(mb_detect_encoding($newValue));

$htmlDiff = new HtmlDiff($oldValue, $newValue);
$result = $htmlDiff->build();

var_dump($result);
var_dump(mb_detect_encoding($result));

//> string(9) "Änderung"
//> string(5) "UTF-8"
//> string(14) "Test Änderung"
//> string(5) "UTF-8"
//> string(74) "test� Test � nderung"
//> string(5) "UTF-8"
```

For some reason `HtmlDiff` breaks the encoding. What confuses me is that the example works perfectly on the http://php-htmldiff.caxy.com/ website. Is this not supported or am I doing something wrong?

### PR DESCRIPTION
**Pull request by iluuu1994**

### CODE REVIEW

**Comment by iluuu1994** [comment]
Fixes #71

**Comment by iluuu1994** [comment]
The thing I don't understand is that the code is working perfectly when I run it via in an isolated environment using PHP's integrated server. When I'm testing it my actual application it fails. I get why it fails (because it didn't use unicode functions until now) but I don't get how it doesn't fail otherwise.

**Comment by iluuu1994** [comment]
Sorry, by the code I mean the old code.

**Comment by jschroed91** [comment]
@iluuu1994 Thank you for submitting this. What stack are you running your actual application on (php version, webserver, etc.)? When it fails, are they PHP errors or just warnings/notices? It could potentially just be the `error_reporting` value being different from the PHP built-in server (cli) versus your web server? I'm not sure.

**Comment by iluuu1994** [comment]
@jschroed91 By "failing" I mean the issue described in #71.

> php-htmldiff v0.1.6  
> PHP 7.0.15 (cli) (built: Jan 17 2017 13:44:27) ( NTS )  
> IIS 10.0.17074.1002

**Comment by iluuu1994** [comment]
@jschroed91 So yeah I wanted to add a simple test but it seems to be already working on master which is what confuses me. When running the exact same code snippet:

```php
$oldValue = 'Änderung';
$newValue = 'Test Änderung';

var_dump($oldValue);
var_dump(mb_detect_encoding($oldValue));
var_dump($newValue);
var_dump(mb_detect_encoding($newValue));

$htmlDiff = new HtmlDiff($oldValue, $newValue);
$result = $htmlDiff->build();

var_dump($result);
var_dump(mb_detect_encoding($result));
```

with the same PHP version and same php-htmldiff version on the same machine BUT in my application all unicode characters get replaced with the `�` character. I have no idea what on earth is actually going on.

Moving to all the `mb_` functions is a good idea nonetheless..

**Comment by SavageTiger** [comment]
Head-sup, migrating to mb_* calls will require the user of the library to have the multibyte php extension installed. I am not sure if this is a unreasonable request. If this pull request is accepted, I would at least add this requirement to the README.

Also I think the strSplitUnicode() function will have a negative performance impact. (Judging from the code)

**Comment by iluuu1994** [comment]
@SavageTiger This library already requires the **php_mbstring** extension:
https://github.com/caxy/php-htmldiff/search?q=mb&type=Code

I removed the `strSplitUnicode` function, it wasn't even necessary.

**Comment by SavageTiger** [comment]
@iluuu1994 Fair enough, I stand corrected :)

**Comment by iluuu1994** [comment]
@SavageTiger Nice 😄 

Correction:

I changed the `explode` function to:

```php
return preg_split('//u', $value, -1, PREG_SPLIT_NO_EMPTY);
```

This prevents makes the function return an empty array instead of `[['', '']]` when splitting empty strings.

**Comment by jschroed91** [comment]
This is looking good.

@SavageTiger did you have any other comments on this one or is it good to go in?

**Comment by SavageTiger** [comment]
@jschroed91 No, since multibyte is already required for this library. And i feel that the performance tradeof is not worth not having proper unicode support. So I say 👍

**Comment by iluuu1994** [comment]
Hey 🙂 

Is this still being considered? I'd like to switch back to a stable release 😄

**Comment by jschroed91** [comment]
Certainly is! I thought I merged this :facepalm: 

I’ll merge and tag in just 30 mins or so - once I’m out of a meeting

**Comment by jschroed91** [comment]
Thank you @iluuu1994 - this has been merged and included in release [v0.1.7](https://github.com/caxy/php-htmldiff/releases/tag/v0.1.7)

**Comment by iluuu1994** [comment]
@jschroed91 Awesome! Thanks for merging

**Pull request merged**
