### PR TITLE
php 8.2: Deprecated function mb_convert_encoding()

### PR DESCRIPTION
**Pull request by s-ayers**
https://github.com/caxy/php-htmldiff/issues/123

### CODE REVIEW

**Comment by christian-kolb** [comment]
Anything we can do to get this merged and a new release published? 🙂

**Comment by heddn** [comment]
I've run the tests locally and they pass green. There are some other Iterator deprecations (in tests only), but that is outside of scope of this. I also reviewed the test coverage of this module to confirm we test `TableDiff::createDocumentWithHtml`, there is 100% test coverage of that method. LGTM.

**Comment by heddn** [comment]
BTW, we depend upon this module in Drupal (its a top 100 module) and we would really like to see this fix merged. See https://www.drupal.org/project/diff/issues/3419173

**Review by jschroed91 — APPROVED** [review]

**Comment by jschroed91** [comment]
Thank you for repinging on this - will get this updated

**Comment by laurisigaunis** [comment]
I get error when patching

> iconv(): Detected an illegal character in input string in Caxy\HtmlDiff\Table\TableDiff->createDocumentWithHtml() (line 630 of /app/vendor/caxy/php-htmldiff/lib/Caxy/HtmlDiff/Table/TableDiff.php)

Adding `//TRANSLIT` solves issue for me. 
Full line: `dom->loadHTML(htmlspecialchars_decode(iconv('UTF-8', 'ISO-8859-1//TRANSLIT', htmlentities($text, ENT_COMPAT, 'UTF-8')), ENT_QUOTES));`

**Pull request merged**
