### PR TITLE
Differ crashed when comparing regular space character in table column.

### PR DESCRIPTION
**Pull request by SavageTiger**
Hi Josh.

See title :)

### CODE REVIEW

**Comment by jschroed91** [comment]
@SavageTiger Yay! Nice catch!

**Comment by jschroed91** [comment]
@SavageTiger Merged! Would you like me to tag a new release? (I still need to add release notes for that last one... :disappointed: )

**Comment by SavageTiger** [comment]
@jschroed91 I think its time. If you want I can make release notes for tomorrow.

**Comment by jschroed91** [comment]
@SavageTiger That would be very helpful if you would like to and have the time to do so. If not, it's not a big deal - it's just a matter of finding the time :smile:

**Pull request merged**
